apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mt-frontend
  labels:
    app: mt-dashboard
    component: frontend
spec:
  source:
    type: Binary
    # "oc start-build mt-frontend --from-dir=./frontend" ile kod gönderilir
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: mt-frontend:latest
  triggers:
    - type: ConfigChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mt-frontend
  labels:
    app: mt-dashboard
    component: frontend
