apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mt-dashboard-frontend
  labels:
    app: mt-dashboard
spec:
  # host alanı boş bırakılırsa OpenShift otomatik URL atar:
  # mt-dashboard-frontend-<namespace>.apps.<cluster-domain>
  to:
    kind: Service
    name: mt-frontend-service
  port:
    targetPort: 8081
  tls:
    termination: edge
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mt-dashboard-backend
  labels:
    app: mt-dashboard
spec:
  # OpenShift otomatik URL atar:
  # mt-dashboard-backend-<namespace>.apps.<cluster-domain>
  to:
    kind: Service
    name: mt-backend-service
  port:
    targetPort: 8080
  tls:
    termination: edge
