apiVersion: v1
kind: Secret
metadata:
  name: mt-dashboard-secrets
  labels:
    app: mt-dashboard
type: Opaque
stringData:
  SECRET_KEY: "BURAYA-GUCLU-BIR-KEY-YAZ"
  # Oracle'a geçince DATABASE_URL buraya taşınacak:
  # DATABASE_URL: "oracle+oracledb://user:pass@host:1521/?service_name=SVC"
